### ISSUE TITLE
Negative Binomial invCDF function throws exceptions when it shouldn't

### ISSUE THREAD

**Issue by bjroden** [rossetti/KSL#2]
At the end of the NegativeBinomial invCDF function, it calls another function and passes parameters in the order p, numSuccesses, probOfSuccess:

https://github.com/rossetti/KSL/blob/614586ffb2c8015ef633603e9681053c398b71b5/KSLCore/src/main/kotlin/ksl/utilities/distributions/NegativeBinomial.kt#L164

This function is expecting the parameters in a different order: p, probOfSuccess, numSuccesses:

https://github.com/rossetti/KSL/blob/614586ffb2c8015ef633603e9681053c398b71b5/KSLCore/src/main/kotlin/ksl/utilities/distributions/NegativeBinomial.kt#L407-L418

This can cause invCDF to throw a "Success Probability must be in (0,1)" exception when it shouldn't, since the function checks if numSuccesses is in (0,1) rather than probOfSuccess.

**Comment by rossetti** [comment]
This has been corrected in R1.0.3
